- name: Install vim & zsh
  apt:
    name: ["vim", "zsh"]
  tags:
    - zsh
- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags:
    - zsh
- name: Install oh-my-zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  tags:
    - zsh
- name: Install zsh autosuggestion
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - zsh
